export enum UserPermission {
  APPROVE_VACATIONS = 'APPROVE_VACATIONS',
  APPROVE_REQUESTS = 'APPROVE_REQUESTS',
  VIEW_ALL_EMPLOYEES = 'VIEW_ALL_EMPLOYEES',
  MANAGE_PAYROLL = 'MANAGE_PAYROLL',
  VIEW_REPORTS = 'VIEW_REPORTS',
}
